### ISSUE TITLE
Can you...

### ISSUE THREAD

**Issue by Filo97** [shinyquagsire23/SaltySD#6]
Can you do that in the directory SaltySD there is an .xml file and we can add the directories for games we want? (or at least can you add pokemon oras?)

**Comment by Cydget** [comment]
Also, this isnt an issue, but can you make a version that can load off the internet. Something like an option in the makefile to load load the changes from a url instead if /saltysd/smash. This way, we could make edits and see the result without even needing to ftp or copy a file.

**Comment by shinyquagsire23** [comment]
@Filo97 At the moment the Smash payloads are wired specifically for Smash, an XYORAS payload would have to be created from scratch for those games. I'll probably end up doing SaltySD for XYORAS and SMD at some point, no ETA on that though.

@Cydget That's unlikely, only because it'd take a lot to even download from a URL, and it'd be super slow to be honest. Not impossible by any means, but definitely slow and difficult to actually code in.

**Comment by Cydget** [comment]
Ya, I know how slow it could be loading from url even if it was small things like the payload for hax2.5 in smashhax using url, but thanks for response.

**Comment by mariohackandglitch** [comment]
This would be very useful for CTGP-7 as well (Mario Kart 7), since setting up layeredfs, NTRCFW, etc can be tricky for some people. Is there any simple way we can search for the file loading functions, so we can use current payload with other games?

**Comment by shinyquagsire23** [comment]
I kinda want to look back at @Cydget's comment in regards to loading files over HTTP. I'm thinking there's two ways to go about this: 

- Have Sm4sh host a server of some sort to allow files to be transferred, when a file is accepted RF entries for that file are updated with proper allocation sizes. 
- Alternatively, have a program (probably a Python script or similar) acting as a server for Sm4sh, and after validating that the file entry exists already and has an SD override set, ping the server to check if there's a server override. If there is, have it return a size and download the file into RAM. It would probably also be good to have a background thread to modify RF entry sizes as soon as the host PC gets changes so that allocations are set right before reading in.

For new files with either, it would probably be easier to do something like https://github.com/Cruel/freeShop/blob/f23d5476f0ddf29aac3a37b8e99fe09c21f75af3/src/States/SyncState.cpp#L187-L195, just restarting the entire app from the game itself. Or somehow re-read ls and the RF files, but I feel that could get messy.
