### ISSUE TITLE
Custom menu music stops playing after a match.

### ISSUE THREAD

**Issue by CorBond57** [shinyquagsire23/SaltySD#7]
Pretty odd how noone picked this up.
Basically custom menu music quits playing after coming back to the menu after a match.
going back to the title screen and then going back into the menu seems to fix this.

**Comment by shinyquagsire23** [comment]
Yeah I'm not sure on this one, because literally all I do is rearrange the loading priority of songs and have it load from sdmc:/saltysd/smash/sound/bgm instead of rom:/patch/sound/bgm. I've definitely had this occur a few times though. Perhaps it's just the audio file itself? Maybe try using the original menu theme or an existing in-game nus3bank and see if the issue occurs.

**Comment by lilggamegenuis** [comment]
I believe its because the music file is too short, Because when you join, It tries to "continue" from where it left off, So it tries to continue after the song ends. I haven't tested this but try getting a longer song and see if it doesn't stop after.

**Comment by LinkTahuterasuSpirit** [comment]
you might need to make sure that the music file loops, it's a bit like Brawl music mods

**Comment by lilggamegenuis** [comment]
I don't think its that because the 3 songs i tested all loop but only 2 of them have ever been silent after returning from a match.
